import Head from 'next/head';
import dynamic from 'next/dynamic';
import { Header, Login } from '@/components';
import { Container, VStack } from '@chakra-ui/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
        <Container
          bg="black"
          backgroundImage="/background.png"
          backgroundSize="cover"
          backgroundRepeat="no-repeat"
          backgroundPosition="top right"
          height="100vh"
          p="8"
          color="white"
          maxW="100%"
        >
          <Header />
          <Login />
        </Container>
      </VStack>
    </>
  );
}
